# Generated by Django 4.1.7 on 2023-10-02 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cloudserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerUserSettings',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('max_cell_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='simulationentry',
            name='max_cell_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulationentry',
            name='title',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='sourcecontententry',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
